export interface LoanCreatedEvent {
  eventType: "Loan.Created";
  reservationId: string;      // Generated by Loan Service
  userId: string;
  deviceId: string;

  // Metadata from Loan Service
  deviceBrand?: string;       // Device brand (e.g., "Apple")
  deviceModel?: string;       // Device model (e.g., "MacBook Pro")
  userEmail?: string;         // User's email address

  startDate: string;          // Default: now
  dueDate: string;            // +2 days (loan duration)

  timestamp: string;          // Event creation time
}
