export interface LoanCreatedEvent {
  eventType: "Loan.Created";
  reservationId: string;      // Generated by Loan Service
  userId: string;
  deviceId: string;

  startDate: string;          // Default: now
  dueDate: string;            // +2 days (loan duration)

  timestamp: string;          // Event creation time
}
